
name: auto-checkin

on:
  schedule:
     # 6个小时一次
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main
      env:
        CONFIG: ${{secrets.CONFIG}}
      run: |
        python main.py
  del_runs:
      runs-on: ubuntu-latest
      permissions:
        actions: write
      steps:
        - name: Delete workflow runs
          uses: Mattraks/delete-workflow-runs@v2
          with:
            token: ${{ github.token }}
            repository: ${{ github.repository }}
            retain_days: 1
            keep_minimum_runs: 6
